services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: almex_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
    env_file:
      - .env
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  web:
    image: nginx:1.27-alpine
    container_name: almex_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  npm:
    image: node:20-alpine
    container_name: almex_vite
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www/html
      - node_modules:/var/www/html/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: almex_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: almex_maintenance_tracker_admin
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: almex
      MYSQL_PASSWORD: almex
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: almex_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  vendor:
  node_modules:
  mysql-data:
  redis-data:
