services:
  app:
    container_name: null          # evita nombre fijo en Portainer
    env_file: []                  # anula el env_file del base
    secrets:
      - source: almex-maintenance_tracker_admin-env-dev
        target: /run/secrets/app_env
        mode: 0440

  queue:
    container_name: null
    env_file: []
    secrets:
      - source: almex-maintenance_tracker_admin-env-dev
        target: /run/secrets/app_env
        mode: 0440

  scheduler:
    container_name: null
    env_file: []
    secrets:
      - source: almex-maintenance_tracker_admin-env-dev
        target: /run/secrets/app_env
        mode: 0440

  web:
    container_name: null

  npm:
    container_name: null

  mysql:
    container_name: null

  redis:
    container_name: null

secrets:
  almex-maintenance_tracker_admin-env-dev:
    external: true
