version: "3.9"

services:
  app:
    image: your-registry/almex-admin-php:dev   # ⬅️ REEMPLAZA por tu imagen publicada
    env_file: []   # anula el env_file del base
    secrets:
      - source: almex-maintenance_tracker_admin-env-dev
        target: /run/secrets/app_env
        mode: 0440
    depends_on:
      - mysql
      - redis
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10

  queue:
    image: your-registry/almex-admin-php:dev
    env_file: []
    secrets:
      - source: almex-maintenance_tracker_admin-env-dev
        target: /run/secrets/app_env
        mode: 0440
    depends_on:
      - mysql
      - redis
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10

  scheduler:
    image: your-registry/almex-admin-php:dev
    env_file: []
    secrets:
      - source: almex-maintenance_tracker_admin-env-dev
        target: /run/secrets/app_env
        mode: 0440
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10

  web:
    depends_on:
      - app
    deploy:
      restart_policy:
        condition: any

  npm:
    depends_on:
      - app
    deploy:
      restart_policy:
        condition: any

  mysql:
    deploy:
      restart_policy:
        condition: any

  redis:
    deploy:
      restart_policy:
        condition: any

secrets:
  almex-maintenance_tracker_admin-env-dev:
    external: true
