
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: almex_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8000:80"
    environment:
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-almex_db}
      - DB_USERNAME=${DB_USERNAME:-almex_user}
      - DB_PASSWORD=${DB_PASSWORD}
      - QUEUE_CONNECTION=database
    depends_on:
      - db
    networks:
      - almex_network
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache

  db:
    image: mysql:8.0
    container_name: almex_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-almex_db}
      - MYSQL_USER=${DB_USERNAME:-almex_user}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - almex_network

networks:
  almex_network:
    driver: bridge

volumes:
  db_data:
    driver: local
